### ISSUE TITLE
always magenta as default

### ISSUE THREAD

**Issue by HernandoMV** [platybrowser/platybrowser-fiji#40] opened 2019-11-08 10:35 UTC
Whenever you add something, it is always in magenta and does not change colors as before.

**Comment by tischi** [comment] 2020-02-08 16:48
>  it is always in magenta 

1. would you prefer another color?

> and does not change colors as before

2. is that still the case?

@vzinche, could you please also comment on both questions?

**Comment by vzinche** [comment] 2020-02-10 09:46
1) Magenta is fine as the first one. What would be nice is to use a different color whenever you add a new image on top. Because right now they are all shown in magenta and you have to change all the subsequent ones manually

2) Yes, at least in the jar that you shared around to test:

![magenta](https://user-images.githubusercontent.com/32451366/74138829-93ad5300-4bf2-11ea-9cb9-5db9268f7370.gif)

**Comment by tischi** [comment] 2020-02-10 19:19
1. I can think about it. Do you have a suggestion? Shall we maybe use the Glasbey LUT?
2. In the version that I ship now with Fiji it should work, does it?

**Comment by vzinche** [comment] 2020-02-11 08:29
1) Glasbey LUT is perfectly fine with me
2) I've just updated the PlatyBrowser in Fiji and no, it still shows everything in magenta

**Comment by tischi** [comment] 2020-02-11 16:38
> Glasbey LUT is perfectly fine with me

@constantinpape For the ProSPr, do you want to put explicit random colours in the `images.json` as r,g,b triplets, e.g. `Color = "255,0,255"` ? Or shall we use a `Color = "RandomFromGlasbey"` convention and I handle this on my side? The advantage of you doing it would be that it would be reproducible and transparent. In fact, I could also  make it reproducible by converting the ProSPr string to always the same random number, using the hashcode of the string, and then, based on this select a random color from the Glasbey. What do you think?

**Comment by tischi** [comment] 2020-02-11 17:27
I implemented the second option.

@constantinpape Could you please adapt `images.json`?

**Comment by constantinpape** [comment] 2020-02-12 07:52
> I implemented the second option.
> 
> @constantinpape Could you please adapt `images.json`?

Ok, will do.
Should I push this to master or put it on some branch first to test it?

**Comment by tischi** [comment] 2020-02-12 07:57
> Should I push this to master or put it on some branch first to test it?

First on a branch please, because I might not have time to adapt my code before tonight, because I will be teaching now the whole day.

**Comment by constantinpape** [comment] 2020-02-12 14:55
Done and pushed it to https://github.com/platybrowser/platybrowser-backend/tree/prospr-glasbey.

**Comment by tischi** [comment] 2020-02-12 16:57
Works! Can you merge to master? And then close the issue?

**Comment by constantinpape** [comment] 2020-02-12 20:48
Done.

**Closed by constantinpape** 2020-02-12 20:48 UTC
Labels: bug

**Comment by constantinpape** [comment] 2020-02-12 20:53
@tischi It seems like you haven't pushed the necessary changes to fiji, so currently the plugin does not work with master.

**Comment by tischi** [comment] 2020-02-13 05:55
You are right. I pushed the wrong version.

I changed back from 

```java
	public static final String remoteGitLocation = "https://raw.githubusercontent.com/platybrowser/platybrowser-backend/prospr-glasbey/data";
```

to 

```java
	public static final String remoteGitLocation = "https://raw.githubusercontent.com/platybrowser/platybrowser-backend/master/data";
```

and uploaded to Fiji again.

Does it work?

**Comment by constantinpape** [comment] 2020-02-13 08:01
Yes it works now.
